.gitignore, BE/.idea/modules.xml, BE/src/main/resources/application.properties
=> [BE/FEAT] gitignore 재설정

BE/src/main/java/com/econovation/rere/apiresponse/ApiError.java, BE/src/main/java/com/econovation/rere/apiresponse/ApiResult.java, BE/src/main/java/com/econovation/rere/apiresponse/ApiUtils.java
- ApiResult 작성
- ApiError 작성
- ApiUtils 작성
-
=> [BE/FEAT] apiresponse 작성

BE/src/main/java/com/econovation/rere/domain/dto/request/BlindCardCreateRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/request/CardBookCreateRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/request/CardBookUpdateRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/request/CardCreateRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/request/CardUpdateRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/request/ThemeCreateRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/request/ThemeUpdateRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/request/UserCreateRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/response/CardBookResponseDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/response/CardResponseDTO.java, BE/src/main/java/com/econovation/rere/domain/entity/BlindCard.java, BE/src/main/java/com/econovation/rere/domain/entity/Card.java, BE/src/main/java/com/econovation/rere/domain/entity/CardBook.java, BE/src/main/java/com/econovation/rere/domain/entity/Session.java, BE/src/main/java/com/econovation/rere/domain/entity/StudyComplete.java, BE/src/main/java/com/econovation/rere/domain/entity/Theme.java, BE/src/main/java/com/econovation/rere/domain/entity/User.java, BE/src/main/java/com/econovation/rere/domain/entity/UserCardBook.java, BE/src/main/java/com/econovation/rere/domain/repository/CardBookRepository.java, BE/src/main/java/com/econovation/rere/domain/repository/CardRepository.java, BE/src/main/java/com/econovation/rere/domain/repository/ThemeRepository.java, BE/src/main/java/com/econovation/rere/domain/repository/UserCardBookRepository.java, BE/src/main/java/com/econovation/rere/domain/repository/UserRepository.java, BE/src/main/java/com/econovation/rere/service/CardBookService.java, BE/src/main/java/com/econovation/rere/service/CardService.java, BE/src/main/java/com/econovation/rere/service/ThemeService.java, BE/src/main/java/com/econovation/rere/service/UserCardBookService.java
- CardBookService 계층
- ThemeService 계층
- CardService 계층
- CardBook, Theme, Card, User DTO를 Request/Response 로 분리해서 구현
- Entity 일부 수정
- Repository 일부 수정
-
=> [BE/FEAT] Service 계층 구현 및 Entity 수정, DTO 생성

BE/build/resources/main/application.properties, BE/src/main/java/com/econovation/rere/config/SecurityConfig.java, BE/src/main/java/com/econovation/rere/controller/UserController.java, BE/src/main/java/com/econovation/rere/domain/dto/request/UserLoginRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/entity/User.java, BE/src/main/java/com/econovation/rere/service/UserService.java
- 로그인 구현
- 스프링 세션 이용
- 패스워드 인코
-
=> [BE/FEAT] 로그인 구현

BE/src/main/java/com/econovation/rere/controller/ThemeController.java
- ThemeController 작성
- 목차 생성
- 카드북에 속한 목차들 조회
- 목차,카드 수정
-
=> [BE/FEAT] ThemeController 구현

BE/src/main/java/com/econovation/rere/controller/CardBookController.java, BE/src/main/java/com/econovation/rere/controller/CardController.java, BE/src/main/java/com/econovation/rere/domain/entity/CardBook.java, BE/src/main/java/com/econovation/rere/domain/entity/StudyComplete.java, BE/src/main/java/com/econovation/rere/domain/entity/Theme.java, BE/src/main/java/com/econovation/rere/domain/entity/User.java, BE/src/main/java/com/econovation/rere/domain/entity/UserCardBook.java, BE/src/main/java/com/econovation/rere/domain/repository/StudyCompleteRepository.java, BE/src/main/java/com/econovation/rere/exception/StudyCompleteNotFoundException.java, BE/src/main/java/com/econovation/rere/service/StudyService.java, BE/src/test/java/com/econovation/rere/repository/UserRepositoryTest.java
- CardController 작성
- 목차에 속한 카드 조회
- 학습 완료
-
=> [BE/FEAT] CardController 구현

BE/src/main/java/com/econovation/rere/controller/UserController.java
=> [BE/FEAT] API url 변경

BE/src/main/java/com/econovation/rere/controller/GlobalExceptionHandler.java, BE/src/main/java/com/econovation/rere/controller/UserController.java, BE/src/main/java/com/econovation/rere/domain/dto/request/UserLoginRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/response/UserLoginResponseDTO.java, BE/src/main/java/com/econovation/rere/domain/entity/User.java, BE/src/main/java/com/econovation/rere/exception/DuplicateLoginIdException.java, BE/src/main/java/com/econovation/rere/exception/DuplicateNicknameException.java, BE/src/main/java/com/econovation/rere/exception/InvalidLoginException.java, BE/src/main/java/com/econovation/rere/exception/InvalidLogoutException.java, BE/src/main/java/com/econovation/rere/service/UserService.java
=> [BE/FEAT] UserController 수정

BE/build.gradle, BE/src/main/java/com/econovation/rere/controller/CardBookController.java, BE/src/main/java/com/econovation/rere/controller/GlobalExceptionHandler.java, BE/src/main/java/com/econovation/rere/domain/dto/request/BlindCardCreateRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/request/CardBookRemoveRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/request/CardBookUpdateRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/request/CardUpdateRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/request/ThemeRemoveRequestDTO.java, BE/src/main/java/com/econovation/rere/exception/NotAthenticationException.java, BE/src/main/java/com/econovation/rere/service/CardBookService.java, BE/src/main/resources/application.properties, BE/src/test/java/com/econovation/rere/repository/CardBookRepositoryTest.java
- 인증 인가 기능을 추가한 CardBook Controller 작성
-
=> [BE/FEAT] cardbook Controller 구현 + 인증/인가 기능 

BE/src/main/java/com/econovation/rere/config/WebConfig.java, BE/src/main/java/com/econovation/rere/controller/CardBookController.java, BE/src/main/java/com/econovation/rere/controller/ThemeController.java, BE/src/main/java/com/econovation/rere/interceptor/LoginInterceptor.java, BE/src/main/java/com/econovation/rere/service/UserCardBookService.java, BE/src/main/resources/application.properties
- 비로그인 사용자일 경우에 대한 로직 추가 (쿠키에 세션이 담겨있지 않을 때)
- CardBook Controller
- Theme Controller
-
=> [BE/FEAT] CardBook and Theme Controller Refactor

BE/src/main/java/com/econovation/rere/config/WebConfig.java, BE/src/main/java/com/econovation/rere/controller/CardBookController.java, BE/src/main/java/com/econovation/rere/controller/GlobalExceptionHandler.java, BE/src/main/java/com/econovation/rere/controller/ThemeController.java, BE/src/main/java/com/econovation/rere/domain/dto/request/UserCreateRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/response/ThemePageResponseDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/response/ThemeResponseDTO.java, BE/src/main/java/com/econovation/rere/exception/DuplicateLoginIdException.java, BE/src/main/java/com/econovation/rere/exception/DuplicateNicknameException.java, BE/src/main/java/com/econovation/rere/service/ThemeService.java, BE/src/main/java/com/econovation/rere/service/UserService.java
- UserLoginRequestDTO에서 @Size , @Pattern 제거
- ExceptionHandler 올바르게 수정
- Service가 예외를 올바르게 던지도록 수정
- 사용자가 한번도 학습을 하지 않았을 경우에 대한 처리 추가
- CORS 정책에서 Preflight 요청 OPTION 메소드 허용
-
=> [BE/FEAT] StudyService refactoring

BE/src/main/java/com/econovation/rere/controller/UserController.java, BE/src/main/java/com/econovation/rere/domain/dto/request/UserNicknameUpdateRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/dto/request/UserPwUpdateRequestDTO.java, BE/src/main/java/com/econovation/rere/domain/entity/User.java, BE/src/main/java/com/econovation/rere/domain/repository/UserRepository.java, BE/src/main/java/com/econovation/rere/interceptor/LoginInterceptor.java, BE/src/main/java/com/econovation/rere/service/UserService.java
- 닉네임 변경 기능 추가
- 비밀번호 변경 기능 추가
-
=> [BE\FEAT] 회원 정보 수정

BE/src/main/java/com/econovation/rere/controller/ThemeController.java, BE/src/main/java/com/econovation/rere/domain/entity/BlindCard.java, BE/src/main/java/com/econovation/rere/domain/entity/Card.java, BE/src/main/java/com/econovation/rere/domain/entity/CardBook.java, BE/src/main/java/com/econovation/rere/domain/entity/StudyComplete.java, BE/src/main/java/com/econovation/rere/domain/entity/Theme.java, BE/src/main/java/com/econovation/rere/domain/entity/User.java
- 모든 엔티티에 대해 Soft Delete 구현
- Cardbook
- Theme
- Card
- User
- BlindCard
- StudyComplete
- UserCardBook
-
=> [BE/FEAT] Soft Delete 구현

BE/src/main/java/com/econovation/rere/config/CurrentUser.java, BE/src/main/java/com/econovation/rere/config/CurrentUserArgumentResolver.java, BE/src/main/java/com/econovation/rere/config/WebConfig.java, BE/src/main/java/com/econovation/rere/controller/CardBookController.java, BE/src/main/java/com/econovation/rere/controller/ThemeController.java, BE/src/main/java/com/econovation/rere/controller/UserController.java
- 현재 로그인된 user 객체를 가져오는 custom annotation
- 그에 따른 컨트롤러 리팩토링
-
=> [BE/FEAT] custom annotation

BE/src/main/java/com/econovation/rere/controller/CardBookController.java, BE/src/main/java/com/econovation/rere/controller/GlobalExceptionHandler.java, BE/src/main/java/com/econovation/rere/domain/dto/request/CardBookUpdateRequestDTO.java, BE/src/main/java/com/econovation/rere/exception/ImageNotLoadException.java, BE/src/main/java/com/econovation/rere/service/CardBookService.java
- 카드북 이미지 예외처리
- 카드북 수정시 이미지도 수정 가능
-
=> [BE/FEAT] 이미지 예외처리, 카드북 이미지 수정 구현

BE/src/main/java/com/econovation/rere/controller/CardBookController.java
=> [BE/FEAT] Cardbook Controller 로그 추가

BE/src/main/java/com/econovation/rere/domain/dto/response/CardBookResponseDTO.java
=> refactor: update updateDate format

BE/src/main/java/com/econovation/rere/service/CardBookService.java
=> [BE/REFCTOR] refactor: admin -> 관리자

BE/src/main/java/com/econovation/rere/domain/dto/response/CardBookResponseDTO.java, BE/src/main/java/com/econovation/rere/service/CardBookService.java
=> [BE/REFACTOR] admin -> 관리자

BE/src/main/java/com/econovation/rere/controller/ThemeController.java, BE/src/main/java/com/econovation/rere/domain/dto/request/CardbookThemesResponseDTO.java
=> [BE/FEAT] 목차 조희 응답 수정

BE/src/main/java/com/econovation/rere/controller/ThemeController.java, BE/src/main/java/com/econovation/rere/domain/dto/request/CardbookThemesResponseDTO.java, BE/src/main/java/com/econovation/rere/service/CardBookService.java
=> [BE/hotfix]

BE/src/main/java/com/econovation/rere/controller/CardBookController.java
=> [Hotfix] 비로그인시 카드 생성/수정/삭제 가능
